// Generated by `fx bind` (FX-0.7-BINDGEN-1).
// Source header: D:\fx\tests\fixtures\bind\smoke_add.h
// Level 1 raw stubs - review before linking. Safe wrappers are hand-written (Level 2).
// Do not treat this as opaque import magic.

module smoke_raw;

// --- skipped / unsupported ---
// skip: preprocessor: #define SMOKE_MAGIC 1
// skip: unsupported C type `FILE *`: void smoke_needs_file(FILE *f);

extern "c" {
    // accumulate two i32 values
    fn smoke_add(a: i32, b: i32) -> i32;
}
