// FX-0.7-BINDGEN-3 — Level 2 safe wrapper over cJSON FFI shim.
// Raw Level 1 stubs: cjson_raw.fx (regenerated by `fx bind`).
// C owns the parse tree; fx only sees Result<i32, core_Err>.
module cjson_safe;

using core;

extern "c" {
    fn cjson_ref_parse_number(json: string) -> i32;
}

/// Parse a JSON number literal (e.g. "42"); Err on failure.
fn parse_number(json: string) -> Result<i32, core_Err> {
    let n = cjson_ref_parse_number(json);
    if (n < 0) {
        return Err(1);
    }
    return Ok(n);
}
