// Generated by `fx bind` (FX-0.7-BINDGEN-1).
// Source header: D:\fx\tests\fixtures\bind\cjson_bind.h
// Level 1 raw stubs - review before linking. Safe wrappers are hand-written (Level 2).
// Do not treat this as opaque import magic.

module cjson_raw;

// --- skipped / unsupported ---
// skip: preprocessor: #define CJSON_BIND_MAGIC 1
// skip: unsupported C type `cJSON *`: cJSON *cJSON_Parse(const char *value);

extern "c" {
    // parse a JSON number literal; return i32 value or -1
    fn cjson_ref_parse_number(json: string) -> i32;
}
