/* Generated by fx-compiler from module `main` */
#include "main.h"
#include "std/map.h"
#include <stddef.h>

#line 5 "D:/fx/public/examples/composition_tally/main.fx"
/* fx: effects: alloc, mut */
/* fx: fn main() -> i32 */
int32_t fx_main_main(void) {
    #line 6 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: region r = arena(...); */
    core_Allocator* r = core_arena_new(core_default_allocator(), (size_t)(16384));
    #line 9 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: let m = ...; */
    fx_Map_string_i32 m = fx_std_map_new(r);
    #line 10 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: m = ...; */
    m = fx_std_map_add_i32(r, m, "parse", 4);
    #line 11 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: m = ...; */
    m = fx_std_map_add_i32(r, m, "typeck", 6);
    #line 12 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: m = ...; */
    m = fx_std_map_add_i32(r, m, "emit", 8);
    #line 13 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: m = ...; */
    m = fx_std_map_add_i32(r, m, "parse", 3);
    #line 14 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: m = ...; */
    m = fx_std_map_add_i32(r, m, "link", 5);
    #line 15 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: m = ...; */
    m = fx_std_map_add_i32(r, m, "typeck", 2);
    #line 18 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: m = ...; */
    m = fx_std_map_add_i32(r, m, "emit", 10);
    #line 19 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: m = ...; */
    m = fx_std_map_add_i32(r, m, "link", 7);
    #line 20 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: m = ...; */
    m = fx_std_map_add_i32(r, m, "parse", -(1));
    #line 22 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: if (...) { ... } */
    if ((fx_std_map_len(m) != 4)) {
        #line 23 "D:/fx/public/examples/composition_tally/main.fx"
        /* fx: return ...; */
        core_mem_reset(r);
        return 1;
    }
    #line 25 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: if (...) { ... } */
    if ((fx_std_map_contains(m, "parse") != 1)) {
        #line 26 "D:/fx/public/examples/composition_tally/main.fx"
        /* fx: return ...; */
        core_mem_reset(r);
        return 2;
    }
    #line 30 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: let sum = ...; */
    int32_t sum = 0;
    #line 31 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: let i = ...; */
    int32_t i = 0;
    #line 32 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: while (...) { ... } */
    while ((i < fx_std_map_len(m))) {
        #line 33 "D:/fx/public/examples/composition_tally/main.fx"
        /* fx: sum = ...; */
        sum = (sum + fx_std_map_nth_value(m, i));
        #line 34 "D:/fx/public/examples/composition_tally/main.fx"
        /* fx: i = ...; */
        i = (i + 1);
    }
    #line 36 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: if (...) { ... } */
    if ((sum != 44)) {
        #line 37 "D:/fx/public/examples/composition_tally/main.fx"
        /* fx: return ...; */
        core_mem_reset(r);
        return 3;
    }
    #line 41 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: m = ...; */
    m = fx_std_map_remove(r, m, "link");
    #line 42 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: m = ...; */
    m = fx_std_map_add_i32(r, m, "link", 10);
    #line 45 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: let total = ...; */
    int32_t total = 0;
    #line 46 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: i = ...; */
    i = 0;
    #line 47 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: while (...) { ... } */
    while ((i < fx_std_map_len(m))) {
        #line 48 "D:/fx/public/examples/composition_tally/main.fx"
        /* fx: total = ...; */
        total = (total + fx_std_map_nth_value(m, i));
        #line 49 "D:/fx/public/examples/composition_tally/main.fx"
        /* fx: i = ...; */
        i = (i + 1);
    }
    #line 51 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: if (...) { ... } */
    if ((total != 42)) {
        #line 52 "D:/fx/public/examples/composition_tally/main.fx"
        /* fx: return ...; */
        core_mem_reset(r);
        return 4;
    }
    #line 54 "D:/fx/public/examples/composition_tally/main.fx"
    /* fx: return ...; */
    core_mem_reset(r);
    return total;
}

