// Level 2 safe wrapper over stb_sprintf FFI shim.
// Raw Level 1 stubs: stb_raw.fx (regenerated by `fx bind`).
// C owns format buffers; fx only sees Result<i32, core_Err>.
module stb_safe;

using core;

extern "c" {
    fn stb_sprintf_ref_format_i32(value: i32) -> i32;
}

/// Format `value` via vendored stb_sprintf; Err if round-trip fails.
fn format_i32(value: i32) -> Result<i32, core_Err> {
    let n = stb_sprintf_ref_format_i32(value);
    if (n < 0) {
        return Err(1);
    }
    return Ok(n);
}
