// Generated by `fx bind`.
// Source header: D:\fx\tests\fixtures\bind\stb_sprintf_bind.h
// Level 1 raw stubs - review before linking. Safe wrappers are hand-written (Level 2).
// Do not treat this as opaque import magic.

module stb_raw;

// --- skipped / unsupported ---
// skip: preprocessor: #define STB_SPRINTF_BIND_MAGIC 1
// skip: cannot split return type / name: int stbsp_snprintf(char *buf, int count, const char *fmt, ...);

extern "c" {
    // format i32 via stbsp_snprintf; return round-trip value or -1
    fn stb_sprintf_ref_format_i32(value: i32) -> i32;
}
